name: Centralized CI Pipeline

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main ]

jobs:
  call-central-workflow:
    uses: HyunchanAn/Dental_000/.github/workflows/reusable-ci.yml@main
    with:
      python_version: "3.11"
      install_opencv: true
      test_command: "pytest Dental_000/tests/tests_008 -v"
